---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: patched
spec:
  selector:
    matchLabels:
      app: patched
  template:
    metadata:
      labels:
        app: patched
      annotations:
        ilya-epifanov.github.io/patcher.patches: |
          - op: add
            path: /spec/containers/0/volumeMounts
            value:
              - name: spark-conf-volume
                mountPath: /spark/conf
              - name: hadoop-conf-volume
                mountPath: /spark/hadoop
              - name: job-specific-conf
                mountPath: /job-specific-conf
          - op: add
            path: /spec/volumes
            value:
              - name: spark-conf-volume
                emptyDir: {}
              - name: hadoop-conf-volume
                emptyDir: {}
              - name: job-specific-conf
                emptyDir: {}
    spec:
      containers:
        - name: patched
          image: "busybox:1.29"
          imagePullPolicy: "IfNotPresent"
          command:
            - sleep
          args:
            - "1000"
          resources:
            limits:
              cpu: 10m
              memory: 16Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: unpatched
spec:
  selector:
    matchLabels:
      app: unpatched
  template:
    metadata:
      labels:
        app: unpatched
    spec:
      containers:
        - name: unpatched
          image: "busybox:1.29"
          imagePullPolicy: "IfNotPresent"
          command:
            - sleep
          args:
            - "1000"
          resources:
            limits:
              cpu: 10m
              memory: 16Mi