---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: selfsigned
  namespace: {{ .Release.Namespace | quote }}
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: patcher-maw-certificate
  namespace: {{ .Release.Namespace | quote }}
spec:
  secretName: patcher-maw-certificate
  dnsNames:
    - patcher-maw.{{ .Release.Namespace }}.svc
  issuerRef:
    name: selfsigned